name: lucasphotography
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
